# urbverde-bff/docker-compose.yml
version: "3.8"

services:
  urbverde-bff:
    build:
      context: .
      args:
        ENV: ${ENV:-develop}
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/app/docs:rw  # Added :rw flag to ensure read-write permissions
    environment:
      - ENV=${ENV:-develop}
    env_file:
      - .env
