# urbverde-bff/docker-compose.yml
version: "3.8"

services:
  urbverde-bff:
    build:
      context: .
      args:
        ENV: ${ENV:-develop}
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/app/docs:rw
    environment:
      - ENV=${ENV:-develop}
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: urbverde-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-urbverde_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: urbverde-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    depends_on:
      - postgres

volumes:
  postgres_data:
