# Docker Compose Local para Teste do Dockerfile
version: "3.8"

services:
  urbverde-bff:
    build:
      context: .  # O contexto aponta para o próprio diretório atual
    ports:
      - "8080:8080"
    environment:
      - ENV=development
    env_file:
      - .env
