// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.urbverde.com.br/",
            "email": "comunica.urbverde@usp.br"
        },
        "license": {
            "name": "???",
            "url": "???"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address/data": {
            "get": {
                "description": "Retorna dados detalhados de localização",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "Retorna dados de localização",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código da localização",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nome ou nome de exibição da localização",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tipo da localização (state/city/country)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/repositories_address.Location"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers_address.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/address/suggestions": {
            "get": {
                "description": "Retorna sugestões baseadas nos dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "Retorna sugestões de endereço",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Texto para buscar sugestões",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repositories_address.CityResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers_address.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/parks/inequality": {
            "get": {
                "description": "Retorna dados de desigualdade para a camada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/parks"
                ],
                "summary": "Retorna dados sobre desigualdade",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/parks/info": {
            "get": {
                "description": "Retorna dados adicionais para a camada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/parks"
                ],
                "summary": "Retorna dados adicionais para a camada de praças e parques",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/parks/ranking": {
            "get": {
                "description": "Retorna dados para a construção do ranking de praças e parques",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/parks"
                ],
                "summary": "Retorna dados de ranking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.RankingData"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/parks/square": {
            "get": {
                "description": "Retorna dados de parques e praças para a camada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/parks"
                ],
                "summary": "Retorna dados dos parques e praças",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/temperature/heat": {
            "get": {
                "description": "Retorna os dados de calor extremo para o município e ano fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/temperature"
                ],
                "summary": "Retorna dados de calor extremo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/temperature/info": {
            "get": {
                "description": "Retorna dados adicionais para o município fornecido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/temperature"
                ],
                "summary": "Retorna dados adicionais",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/temperature/ranking": {
            "get": {
                "description": "Retorna os dados de ranking em clima para o município e ano fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/temperature"
                ],
                "summary": "Retorna dados de ranking de clima",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.RankingData"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/temperature/weather": {
            "get": {
                "description": "Retorna os dados de temperatura para o município e ano fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/temperature"
                ],
                "summary": "Retorna dados de temperatura",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/vegetation/cover": {
            "get": {
                "description": "Retorna dados relacionados à cobertura vegetal para o município fornecido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/vegetation"
                ],
                "summary": "Retorna dados relacionados à cobertura vegetal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/vegetation/inequality": {
            "get": {
                "description": "Retorna dados relacionados à desigualdade ambiental e a vegetação para o município fornecido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/vegetation"
                ],
                "summary": "Retorna dados relacionados à desigualdade ambiental e a vegetação",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/vegetation/info": {
            "get": {
                "description": "Retorna dados adicionais para a camada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/vegetation"
                ],
                "summary": "Retorna dados adicionais para a vegetação",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/vegetation/ranking": {
            "get": {
                "description": "Retorna dados para a construção do ranking de desigualdade ambiental e a vegetação",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/vegetation"
                ],
                "summary": "Retorna dados de ranking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.RankingData"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "Retorna as categorias e camadas disponíveis para o município",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "Retorna categorias disponíveis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código do município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/repositories_categories.CategoriesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers_categories.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cards.CardsDataItem": {
            "type": "object",
            "properties": {
                "subtitle": {
                    "type": "string",
                    "example": "Abaixo da média nacional de 0"
                },
                "title": {
                    "type": "string",
                    "example": "Nível de ilha de calor"
                },
                "value": {
                    "type": "string",
                    "example": "25°C"
                }
            }
        },
        "cards.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Erro ao processar a solicitação"
                }
            }
        },
        "cards.RankingData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cards.RankingDataItem"
                    }
                },
                "subtitle": {
                    "type": "string",
                    "example": "Posição do seu município entre os 645 do Estado de São Paulo"
                },
                "title": {
                    "type": "string",
                    "example": "Municipios do Estado"
                }
            }
        },
        "cards.RankingDataItem": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "of": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "controllers_address.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "MISSING_PARAMETERS"
                },
                "message": {
                    "type": "string",
                    "example": "Erro ao processar a solicitação"
                }
            }
        },
        "controllers_categories.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Erro ao processar a solicitação"
                }
            }
        },
        "repositories_address.CenterOpts": {
            "type": "object",
            "properties": {
                "bbox": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        -46.8264,
                        -24.0082,
                        -46.3652,
                        -23.3566
                    ]
                },
                "lat": {
                    "type": "number",
                    "example": -23.5505
                },
                "lng": {
                    "type": "number",
                    "example": -46.6333
                },
                "zoom": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "repositories_address.CityResponse": {
            "description": "City suggestion response model",
            "type": "object",
            "properties": {
                "cd_mun": {
                    "description": "City ID for internal use",
                    "type": "integer",
                    "example": 3550308
                },
                "display_name": {
                    "description": "What user sees: \"City Name - ST\"",
                    "type": "string",
                    "example": "São Paulo - SP"
                }
            }
        },
        "repositories_address.Location": {
            "description": "Detailed location data model",
            "type": "object",
            "properties": {
                "center_options": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/repositories_address.CenterOpts"
                    }
                },
                "code": {
                    "type": "string",
                    "example": "3550308"
                },
                "country": {
                    "type": "string",
                    "example": "Brasil"
                },
                "country_code": {
                    "type": "string",
                    "example": "BR"
                },
                "display_name": {
                    "type": "string",
                    "example": "São Paulo - SP"
                },
                "name": {
                    "type": "string",
                    "example": "São Paulo"
                },
                "state": {
                    "type": "string",
                    "example": "SP"
                },
                "state_name": {
                    "type": "string",
                    "example": "São Paulo"
                },
                "type": {
                    "type": "string",
                    "example": "city"
                }
            }
        },
        "repositories_categories.CategoriesResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repositories_categories.Category"
                    }
                }
            }
        },
        "repositories_categories.Category": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "layers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repositories_categories.Layer"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "repositories_categories.Layer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isNew": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "UrbVerde BFF",
	Description:      "API para fornecer sugestões de endereço e outros serviços relacionados",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
