// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address/suggestions": {
            "get": {
                "description": "Retorna sugestões baseadas nos dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "address"
                ],
                "summary": "Retorna sugestões de endereço",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Texto para buscar sugestões",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/address.AddressSuggestion"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/address.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/weather/heat": {
            "get": {
                "description": "Retorna os dados de calor extremo para o município e ano fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/weather"
                ],
                "summary": "Retorna dados de calor extremo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/weather/info": {
            "get": {
                "description": "Retorna dados adicionais para o município fornecido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/weather"
                ],
                "summary": "Retorna dados adicionais",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/weather/ranking": {
            "get": {
                "description": "Retorna os dados de ranking em clima para o município e ano fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/weather"
                ],
                "summary": "Retorna dados de ranking de clima",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.RankingData"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cards/weather/temperature": {
            "get": {
                "description": "Retorna os dados de temperatura para o município e ano fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards/weather"
                ],
                "summary": "Retorna dados de temperatura",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código de município",
                        "name": "city",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ano dos dados",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cards.CardsDataItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/cards.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "address.AddressSuggestion": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "address.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cards.CardsDataItem": {
            "type": "object",
            "properties": {
                "subtitle": {
                    "type": "string",
                    "example": "Abaixo da média nacional de 0"
                },
                "title": {
                    "type": "string",
                    "example": "Nível de ilha de calor"
                },
                "value": {
                    "type": "string",
                    "example": "25°C"
                }
            }
        },
        "cards.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Erro ao processar a solicitação"
                }
            }
        },
        "cards.RankingData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cards.RankingDataItem"
                    }
                },
                "subtitle": {
                    "type": "string",
                    "example": "Posição do seu município entre os 645 do Estado de São Paulo"
                },
                "title": {
                    "type": "string",
                    "example": "Municipios do Estado"
                }
            }
        },
        "cards.RankingDataItem": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "of": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "UrbVerde BFF",
	Description:      "API para fornecer sugestões de endereço e outros serviços relacionados",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
