basePath: /v1
definitions:
  cards.CardsDataItem:
    properties:
      subtitle:
        example: Abaixo da média nacional de 0
        type: string
      title:
        example: Nível de ilha de calor
        type: string
      value:
        example: 25°C
        type: string
    type: object
  cards.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Erro ao processar a solicitação
        type: string
    type: object
  cards.RankingData:
    properties:
      items:
        items:
          $ref: '#/definitions/cards.RankingDataItem'
        type: array
      subtitle:
        example: Posição do seu município entre os 645 do Estado de São Paulo
        type: string
      title:
        example: Municipios do Estado
        type: string
    type: object
  cards.RankingDataItem:
    properties:
      number:
        type: integer
      of:
        type: integer
      type:
        type: string
    type: object
  controllers_address.ErrorResponse:
    properties:
      error:
        example: MISSING_PARAMETERS
        type: string
      message:
        example: Erro ao processar a solicitação
        type: string
    type: object
  controllers_categories.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Erro ao processar a solicitação
        type: string
    type: object
  repositories_address.CenterOpts:
    properties:
      bbox:
        example:
        - -46.8264
        - -24.0082
        - -46.3652
        - -23.3566
        items:
          type: number
        type: array
      lat:
        example: -23.5505
        type: number
      lng:
        example: -46.6333
        type: number
      zoom:
        example: 10
        type: integer
    type: object
  repositories_address.CityResponse:
    description: City suggestion response model
    properties:
      cd_mun:
        description: City ID for internal use
        example: 3550308
        type: integer
      display_name:
        description: 'What user sees: "City Name - ST"'
        example: São Paulo - SP
        type: string
    type: object
  repositories_address.Location:
    description: Detailed location data model
    properties:
      center_options:
        additionalProperties:
          $ref: '#/definitions/repositories_address.CenterOpts'
        type: object
      code:
        example: "3550308"
        type: string
      country:
        example: Brasil
        type: string
      country_code:
        example: BR
        type: string
      display_name:
        example: São Paulo - SP
        type: string
      name:
        example: São Paulo
        type: string
      state:
        example: SP
        type: string
      state_name:
        example: São Paulo
        type: string
      type:
        example: city
        type: string
    type: object
  repositories_categories.CategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/repositories_categories.Category'
        type: array
    type: object
  repositories_categories.Category:
    properties:
      icon:
        type: string
      id:
        type: string
      layers:
        items:
          $ref: '#/definitions/repositories_categories.Layer'
        type: array
      name:
        type: string
    type: object
  repositories_categories.Layer:
    properties:
      id:
        type: string
      isActive:
        type: boolean
      isNew:
        type: boolean
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: comunica.urbverde@usp.br
    name: API Support
    url: http://www.urbverde.com.br/
  description: API para fornecer sugestões de endereço e outros serviços relacionados
  license:
    name: ???
    url: ???
  title: UrbVerde BFF
  version: "1.0"
paths:
  /address/data:
    get:
      consumes:
      - application/json
      description: Retorna dados detalhados de localização
      parameters:
      - description: Código da localização
        in: query
        name: code
        type: string
      - description: Nome ou nome de exibição da localização
        in: query
        name: name
        type: string
      - description: Tipo da localização (state/city/country)
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repositories_address.Location'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers_address.ErrorResponse'
      summary: Retorna dados de localização
      tags:
      - address
  /address/suggestions:
    get:
      consumes:
      - application/json
      description: Retorna sugestões baseadas nos dados fornecidos
      parameters:
      - description: Texto para buscar sugestões
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repositories_address.CityResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers_address.ErrorResponse'
      summary: Retorna sugestões de endereço
      tags:
      - address
  /cards/square/inequality:
    get:
      consumes:
      - application/json
      description: Retorna dados de desigualdade para a camada
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados sobre desigualdade
      tags:
      - cards/square
  /cards/square/info:
    get:
      consumes:
      - application/json
      description: Retorna dados adicionais para a camada
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados adicionais para a camada de praças e parques
      tags:
      - cards/square
  /cards/square/parks:
    get:
      consumes:
      - application/json
      description: Retorna dados de parques e praças para a camada
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados dos parques e praças
      tags:
      - cards/square
  /cards/square/ranking:
    get:
      consumes:
      - application/json
      description: Retorna dados para a construção do ranking de praças e parques
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.RankingData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de ranking
      tags:
      - cards/square
  /cards/temperature/heat:
    get:
      consumes:
      - application/json
      description: Retorna os dados de calor extremo para o município e ano fornecidos
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de calor extremo
      tags:
      - cards/temperature
  /cards/temperature/info:
    get:
      consumes:
      - application/json
      description: Retorna dados adicionais para o município fornecido
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados adicionais
      tags:
      - cards/temperature
  /cards/temperature/ranking:
    get:
      consumes:
      - application/json
      description: Retorna os dados de ranking em clima para o município e ano fornecidos
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.RankingData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de ranking de clima
      tags:
      - cards/temperature
  /cards/temperature/weather:
    get:
      consumes:
      - application/json
      description: Retorna os dados de temperatura para o município e ano fornecidos
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de temperatura
      tags:
      - cards/temperature
  /cards/vegetation/cover:
    get:
      consumes:
      - application/json
      description: Retorna dados relacionados à cobertura vegetal para o município
        fornecido
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados relacionados à cobertura vegetal
      tags:
      - cards/vegetation
  /cards/vegetation/inequality:
    get:
      consumes:
      - application/json
      description: Retorna dados relacionados à desigualdade ambiental e a vegetação
        para o município fornecido
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados relacionados à desigualdade ambiental e a vegetação
      tags:
      - cards/vegetation
  /cards/vegetation/info:
    get:
      consumes:
      - application/json
      description: Retorna dados adicionais para a camada
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados adicionais para a vegetação
      tags:
      - cards/vegetation
  /cards/vegetation/ranking:
    get:
      consumes:
      - application/json
      description: Retorna dados para a construção do ranking de desigualdade ambiental
        e a vegetação
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.RankingData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de ranking
      tags:
      - cards/vegetation
  /categories:
    get:
      consumes:
      - application/json
      description: Retorna as categorias e camadas disponíveis para o município
      parameters:
      - description: Código do município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repositories_categories.CategoriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers_categories.ErrorResponse'
      summary: Retorna categorias disponíveis
      tags:
      - categories
swagger: "2.0"
