basePath: /v1
definitions:
  address.AddressSuggestion:
    properties:
      address:
        type: string
      id:
        type: integer
    type: object
  address.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  cards.CardsDataItem:
    properties:
      subtitle:
        example: Abaixo da média nacional de 0
        type: string
      title:
        example: Nível de ilha de calor
        type: string
      value:
        example: 25°C
        type: string
    type: object
  cards.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Erro ao processar a solicitação
        type: string
    type: object
  cards.RankingData:
    properties:
      items:
        items:
          $ref: '#/definitions/cards.RankingDataItem'
        type: array
      subtitle:
        example: Posição do seu município entre os 645 do Estado de São Paulo
        type: string
      title:
        example: Municipios do Estado
        type: string
    type: object
  cards.RankingDataItem:
    properties:
      number:
        type: integer
      of:
        type: integer
      type:
        type: string
    type: object
  controllers_categories.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Erro ao processar a solicitação
        type: string
    type: object
  repositories_categories.CategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/repositories_categories.Category'
        type: array
    type: object
  repositories_categories.Category:
    properties:
      icon:
        type: string
      id:
        type: string
      layers:
        items:
          $ref: '#/definitions/repositories_categories.Layer'
        type: array
      name:
        type: string
    type: object
  repositories_categories.Layer:
    properties:
      id:
        type: string
      isActive:
        type: boolean
      isNew:
        type: boolean
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: comunica.urbverde@usp.br
    name: API Support
    url: http://www.urbverde.com.br/
  description: API para fornecer sugestões de endereço e outros serviços relacionados
  license:
    name: ???
    url: ???
  title: UrbVerde BFF
  version: "1.0"
paths:
  /address/suggestions:
    get:
      consumes:
      - application/json
      description: Retorna sugestões baseadas nos dados fornecidos
      parameters:
      - description: Texto para buscar sugestões
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/address.AddressSuggestion'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/address.ErrorResponse'
      summary: Retorna sugestões de endereço
      tags:
      - address
  /cards/weather/heat:
    get:
      consumes:
      - application/json
      description: Retorna os dados de calor extremo para o município e ano fornecidos
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de calor extremo
      tags:
      - cards/weather
  /cards/weather/info:
    get:
      consumes:
      - application/json
      description: Retorna dados adicionais para o município fornecido
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados adicionais
      tags:
      - cards/weather
  /cards/weather/ranking:
    get:
      consumes:
      - application/json
      description: Retorna os dados de ranking em clima para o município e ano fornecidos
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.RankingData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de ranking de clima
      tags:
      - cards/weather
  /cards/weather/temperature:
    get:
      consumes:
      - application/json
      description: Retorna os dados de temperatura para o município e ano fornecidos
      parameters:
      - description: Código de município
        in: query
        name: city
        required: true
        type: string
      - description: Ano dos dados
        in: query
        name: year
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cards.CardsDataItem'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/cards.ErrorResponse'
      summary: Retorna dados de temperatura
      tags:
      - cards/weather
  /categories:
    get:
      consumes:
      - application/json
      description: Retorna as categorias e camadas disponíveis para o município
      parameters:
      - description: Código do município
        in: query
        name: city
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repositories_categories.CategoriesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers_categories.ErrorResponse'
      summary: Retorna categorias disponíveis
      tags:
      - categories
swagger: "2.0"
