name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/urbverde-bff:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/urbverde-bff:latest

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          set -e  # Exit on any error
          
          echo "Starting deployment..."
          cd /home/${{ secrets.PRODUCTION_USER }}/sphere-api-stack/urbverde-bff
          
          echo "Current git status:"
          git status
          
          echo "Current git remote:"
          git remote -v
          
          echo "Fetching latest changes..."
          git remote set-url origin https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/UrbVerde/urbverde-bff.git
          git fetch origin main
          
          echo "Checking differences..."
          git rev-list HEAD...origin/main --count
          
          echo "Resetting to latest main..."
          git reset --hard origin/main
          
          echo "Verifying update..."
          git log -1 --oneline
          ls -la
          
          echo "Building docker image..."
          docker build -t urbverde/urbverde-bff:latest .
          
          echo "Starting container with parent compose..."
          cd ..
          docker-compose up -d --no-deps urbverde-bff
          
          echo "Deployment complete"