name: Deploy to Production

on:
  push:
    branches:
      - main  # Ou a branch principal do repositório

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/urbverde-bff:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/urbverde-bff:latest

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          cd /home/${{ secrets.PRODUCTION_USER }}/sphere-api-stack

          # Clone o repositório caso não exista, ou atualize com git pull
          if [ ! -d "urbverde-bff" ]; then
            git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/UrbVerde/urbverde-bff.git
          else
            cd urbverde-bff
            git pull origin main  # Atualiza a branch principal
            cd ..
          fi

          # Atualize a imagem Docker e reinicie o serviço específico
          docker-compose pull urbverde-bff
          docker-compose up -d --no-deps --build urbverde-bff
      