name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/urbverde-bff:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/urbverde-bff:latest

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USER }}
        password: ${{ secrets.PRODUCTION_PASSWORD }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          cd /home/${{ secrets.PRODUCTION_USER }}/sphere-api-stack/
          
          # Clone or update repository with error checking
          if [ ! -d "urbverde-bff" ]; then
            echo "Directory doesn't exist. Cloning..."
            git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/UrbVerde/urbverde-bff.git
            if [ $? -ne 0 ]; then
              echo "Failed to clone repository"
              exit 1
            fi
          else
            echo "Directory exists. Updating..."
            cd urbverde-bff
            # Force clean any local changes
            git reset --hard
            git clean -fd
            # Check current branch
            echo "Current branch:"
            git branch
            # Force pull latest main
            git fetch origin
            git checkout main
            git pull origin main --force
            if [ $? -ne 0 ]; then
              echo "Failed to pull latest changes"
              exit 1
            fi
            cd ..
          fi

          # Build and run
          cd urbverde-bff
          echo "Building docker image..."
          docker build -t urbverde/urbverde-bff:latest .
          
          cd ..
          echo "Starting container..."
          docker-compose up -d --no-deps urbverde-bff
      